---

- name: Get checksums from github.com
  set_fact:
    _checksums: "{{ lookup('url', prometheus_jitsi_meet_exporter_checksum_url, wantlist=True) | list }}"
  run_once: true

- name: "Get checksum for {{ go_arch_map[ansible_architecture] | default(ansible_architecture) }} architecture"
  set_fact:
    exporter_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ _checksums }}"
  when: "('linux-' + (go_arch_map[ansible_architecture] | default(ansible_architecture))) in item"

- name: Ensure prometheus-jitsi-meet-exporter binary is downloaded
  become: false
  get_url:
    url: "{{ prometheus_jitsi_meet_exporter_download_url }}"
    dest: "{{ prometheus_jitsi_meet_exporter_tmp_file }}"
    checksum: "sha512:{{ exporter_checksum }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false

- name: Ensure prometheus-jitsi-meet-exporter binary is in place
  copy:
    src: "{{ prometheus_jitsi_meet_exporter_tmp_file }}"
    dest: "/usr/local/bin/prometheus-jitsi-meet-exporter"
    mode: 0755
  notify: restart prometheus-jitsi-meet-exporter
  when: not ansible_check_mode

- name: Copy prometheus-jitsi-meet-exporter systemd unit
  template:
    src: prometheus-jitsi-meet-exporter.service.j2
    dest: /etc/systemd/system/prometheus-jitsi-meet-exporter.service
    owner: root
    group: root
    mode: 0644
  notify: reload systemd and restart prometheus-jitsi-meet-exporter

- name: Flush handlers
  meta: flush_handlers

- name: Enable prometheus-jitsi-meet-exporter service
  service:
    name: prometheus-jitsi-meet-exporter
    state: started
    enabled: yes
