---

- name: Reload systemd and restart prometheus-jitsi-meet-exporter
  systemd:
    daemon_reload: yes
  notify: Restart prometheus-jitsi-meet-exporter

- name: Restart prometheus-jitsi-meet-exporter
  service:
    name: prometheus-jitsi-meet-exporter
    state: restarted
